Repository streetmix/streetmix, pull requests merged in 2018-10, with the labels that each got.

#1153 Incorporates changes from Russian review; new strings also added to translation files
  assets/locales/ar/main.json
  assets/locales/de/main.json
  assets/locales/es-MX/main.json
  assets/locales/es/main.json
  assets/locales/fi/main.json
  assets/locales/fr/main.json
  assets/locales/ja/main.json
  assets/locales/pl/main.json
  assets/locales/pt-BR/main.json
  assets/locales/ru/main.json
  assets/locales/ru/segment-info.json
  assets/locales/sv/main.json
  assets/locales/zh-Hans/main.json
  assets/locales/zh-Hant/main.json
  assets/locales/zh-Hant/segment-info.json
Labels: in progress, translations

#1128 Switches Russian to level 3
  app/data/locales.json
  assets/scripts/dialogs/AboutDialog.jsx
Labels: translations

#1158 Switch Slack to Discord
  README.md
  assets/css/_menus.scss
  assets/locales/en/main.json
  assets/scripts/dialogs/AboutDialog.jsx
  assets/scripts/menus/ContactMenu.jsx
  assets/scripts/ui/Icon.jsx
Labels: in progress

#1159 GalleryStreetItem: use mock canvas for testing
  .travis.yml
  assets/scripts/gallery/GalleryStreetItem.jsx
  package-lock.json
  package.json
  test/setup-jest.js
Labels: in progress

#1160 We didn't need moment.js anymore. Resolves #1152
  assets/scripts/app/DateTimeRelative.jsx
  assets/scripts/app/__tests__/DateTimeRelative.test.js
  package-lock.json
  package.json
  test/setup-jest.js
Labels: in progress

#1161 fixed warning appearing in console
  assets/scripts/streets/StreetMetaWidth.jsx
Labels: in progress

#1163 Building flags
  app/data/flags.json
  assets/scripts/segments/Building.jsx
  assets/scripts/streets/data_model.js
  assets/scripts/streets/width.js
Labels: in progress
