Repository streetmix/streetmix, pull requests merged in 2018-06, with the labels that each got.

#1028 Update Auth0 Twitter access token error message and redirect uri
  app/controllers/twitter_auth0_sign_in_callback.js
Labels: ready

#1034 Add tooltip translation strings for flex segments
  assets/locales/en/segment-info.json
  assets/scripts/segments/info.json
  assets/scripts/segments/variant_icons.js
Labels: translations

#1038 Make Chinese (Traditional) & Portuguese (Br) level 2
  app/data/locales.json
Labels: translations

#1037 Simplify flex segment names
  assets/locales/en/segment-info.json
  assets/scripts/segments/info.json
Labels: translations

#1035 Remove duplicate language key
  assets/locales/en/main.json
Labels: translations

#1060 Update translation files- Polish and Finnish now ready
  assets/locales/ar/main.json
  assets/locales/de/main.json
  assets/locales/es-MX/main.json
  assets/locales/es/main.json
  assets/locales/fi/main.json
  assets/locales/fr/main.json
  assets/locales/ja/main.json
  assets/locales/pl/main.json
  assets/locales/pl/segment-info.json
  assets/locales/pt-BR/main.json
  assets/locales/sv/main.json
  assets/locales/zh-Hant/main.json
  assets/locales/zh-Hant/segment-info.json
Labels: translations

#1027 Email authentication
  app.js
  app/controllers/email_sign_in.js
  app/data/flags.json
  app/models/__mocks__/user.js
  app/models/user.js
  app/resources/v1/__tests__/users.test.js
  app/resources/v1/users.js
  assets/css/_buttons.scss
  assets/css/_dialogs.scss
  assets/locales/en/main.json
  assets/scripts/app/BlockingError.jsx
  assets/scripts/app/__tests__/BlockingError.test.js
  assets/scripts/app/config.js
  assets/scripts/app/errors.js
  assets/scripts/app/routing.js
  assets/scripts/dialogs/DialogRoot.jsx
  assets/scripts/dialogs/EmailSignInDialog.jsx
  assets/scripts/dialogs/__tests__/EmailSignInDialog.test.js
  assets/scripts/gallery/Gallery.jsx
  assets/scripts/menus/MenuBar.jsx
  assets/scripts/menus/MenusContainer.jsx
  assets/scripts/menus/SignInMenu.jsx
  assets/scripts/menus/__tests__/SignInMenu.test.js
  config/default.js
Labels: not-ready

#1068 Add Chinese translators to humans.txt
  public/humans.txt
Labels: translations

#1072 Add French translations for flex zone"
  assets/locales/ar/main.json
  assets/locales/de/main.json
  assets/locales/es-MX/main.json
  assets/locales/es/main.json
  assets/locales/fi/main.json
  assets/locales/fr/main.json
  assets/locales/fr/segment-info.json
  assets/locales/ja/main.json
  assets/locales/pl/main.json
  assets/locales/pt-BR/main.json
  assets/locales/sv/main.json
  assets/locales/zh-Hant/main.json
Labels: translations

#1075 Fix Translation Issue
  assets/locales/en/main.json
  assets/scripts/menus/MenuBar.jsx
  assets/scripts/menus/SignInMenu.jsx
Labels: translations
