Repository streetmix/streetmix, pull requests merged in 2018-08, with the labels that each got.

#1112 Add Simplified Chinese + related updates
  app/data/locales.json
  assets/locales/en/main.json
  assets/scripts/locales/locale.js
Labels: translations

#1120 Add Arabic and Russian translators to humans.txt
  public/humans.txt
Labels: translations

#1126 Fix Arabic issues in #1122
  assets/css/_menus.scss
Labels: localization

#1123 Add Chinese reviewer and update Chinese language title in humans.txt
  public/humans.txt
Labels: translations

#1124 Brings in Arabic and Chinese translations for launch
  assets/locales/ar/main.json
  assets/locales/ar/segment-info.json
  assets/locales/zh-Hans/main.json
  assets/locales/zh-Hans/segment-info.json
  assets/locales/zh-Hant/main.json
  assets/locales/zh-Hant/segment-info.json
Labels: translations

#1119 Turns on Simplified Chinese & Traditional Chinese
  app/data/locales.json
Labels: translations

#1134 initialize state in constructor so warning no longer pops up in console
  assets/scripts/info_bubble/Variants.jsx
Labels: in progress

#1132 GeotagDialog improvements.
  app/resources/services/geoip.js
  assets/scripts/dialogs/Geotag/LocationPopup.jsx
  assets/scripts/dialogs/Geotag/SearchAddress.jsx
  assets/scripts/dialogs/Geotag/__tests__/LocationPopup.test.js
  assets/scripts/dialogs/Geotag/__tests__/SearchAddress.test.js
  assets/scripts/dialogs/Geotag/__tests__/fixtures/autocomplete.json
  assets/scripts/dialogs/Geotag/__tests__/fixtures/search.json
  assets/scripts/dialogs/GeotagDialog.jsx
  assets/scripts/dialogs/__tests__/GeotagDialog.test.js
  assets/scripts/gallery/fetch_street.js
  assets/scripts/store/actions/index.js
  assets/scripts/store/actions/map.js
  assets/scripts/store/reducers/map.js
  assets/scripts/streets/__tests__/fixtures/search.json
  package-lock.json
  package.json
Labels: in progress

#1135 Input controls
  assets/scripts/info_bubble/BuildingHeightControl.jsx
  assets/scripts/info_bubble/WidthControl.jsx
  assets/scripts/segments/__tests__/buildings.test.js
  assets/scripts/segments/buildings.js
Labels: in progress

#1136 Extract common functionality between width and height controls
  assets/css/_info-bubble.scss
  assets/css/_segment.scss
  assets/css/_up-down-input.scss
  assets/css/styles.scss
  assets/scripts/app/keyboard_commands.js
  assets/scripts/app/keys.js
  assets/scripts/info_bubble/BuildingHeightControl.jsx
  assets/scripts/info_bubble/UpDownInput.jsx
  assets/scripts/info_bubble/WidthControl.jsx
  assets/scripts/info_bubble/__tests__/UpDownInput.test.js
  assets/scripts/segments/Building.jsx
  assets/scripts/segments/Segment.jsx
Labels: in progress

#1137 Improve palette tooltips, resolves #833
  assets/css/_palette.scss
  assets/css/_palette.tooltip.scss
  assets/css/styles.scss
  assets/scripts/app/Palette.jsx
  assets/scripts/palette/PaletteTooltips.jsx
  assets/scripts/segments/SegmentForPalette.jsx
  assets/scripts/ui/Scrollable.jsx
Labels: in progress

#1138 Whats new dialog. Resolves #1133.
  app.js
  app/data/flags.json
  app/views/main.hbs
  assets/css/_dialogs.whats-new.scss
  assets/css/styles.scss
  assets/locales/en/main.json
  assets/scripts/app/initialization.js
  assets/scripts/dialogs/DialogRoot.jsx
  assets/scripts/dialogs/WhatsNewDialog.jsx
  public/pages/whats-new/flex-items.png
  public/pages/whats-new/index.html
Labels: in progress
