Repository streetmix/streetmix, pull requests merged in 2018-03, with the labels that each got.

#848 Update Placeholder to use {{}}
  assets/locales/en/main.json
Labels: in progress, translations

#846 Completed tests for GeotagDialog component
  assets/scripts/dialogs/__tests__/GeotagDialog.test.js
Labels: in progress

#849 Remove extraneous geolocate key
  assets/locales/en/main.json
Labels: in progress

#843 Use react-intl library for some translations
  assets/css/_menu-bar.scss
  assets/css/_no-internet.scss
  assets/scripts/app/App.jsx
  assets/scripts/app/Palette.jsx
  assets/scripts/app/UndoRedo.jsx
  assets/scripts/app/__tests__/UndoRedo.test.js
  assets/scripts/app/initialization.js
  assets/scripts/app/locale.js
  assets/scripts/dialogs/AboutDialog.jsx
  assets/scripts/dialogs/Dialog.jsx
  assets/scripts/dialogs/SaveAsImageDialog.jsx
  assets/scripts/dialogs/__tests__/Dialog.test.js
  assets/scripts/dialogs/__tests__/SaveAsImageDialog.test.js
  assets/scripts/menus/ContactMenu.jsx
  assets/scripts/menus/ContributeMenu.jsx
  assets/scripts/menus/EnvironmentBadge.jsx
  assets/scripts/menus/HelpMenu.jsx
  assets/scripts/menus/IdentityMenu.jsx
  assets/scripts/menus/LocaleDropdown.jsx
  assets/scripts/menus/MenuBar.jsx
  assets/scripts/menus/MenuBarItem.jsx
  assets/scripts/menus/MenusContainer.jsx
  assets/scripts/menus/SettingsMenu.jsx
  assets/scripts/menus/ShareMenu.jsx
  assets/scripts/menus/__tests__/ContactMenu.test.js
  assets/scripts/menus/__tests__/ContributeMenu.test.js
  assets/scripts/menus/__tests__/EnvironmentBadge.test.js
  assets/scripts/menus/__tests__/HelpMenu.test.js
  assets/scripts/menus/__tests__/IdentityMenu.test.js
  assets/scripts/menus/__tests__/MenuBarItem.test.js
  assets/scripts/menus/__tests__/SettingsMenu.test.js
  assets/scripts/menus/__tests__/ShareMenu.test.js
  assets/scripts/store/actions/__tests__/locale.test.js
  assets/scripts/store/actions/index.js
  assets/scripts/store/actions/locale.js
  assets/scripts/store/actions/persistSettings.js
  assets/scripts/store/reducers/__tests__/persistSettings.test.js
  assets/scripts/store/reducers/index.js
  assets/scripts/store/reducers/locale.js
  assets/scripts/store/reducers/persistSettings.js
  assets/scripts/streets/StreetMetaData.jsx
  assets/scripts/streets/__tests__/StreetMetaData.test.js
  assets/scripts/users/localization.js
  assets/scripts/users/settings.js
  package-lock.json
  package.json
  test/__mocks__/react-intl.js
Labels: in progress

#854 Adopt single brackets in translation string placeholders
  assets/locales/en/main.json
  assets/scripts/app/locale.js
  assets/scripts/gallery/Gallery.jsx
  assets/scripts/gallery/GalleryStreetItem.jsx
  assets/scripts/streets/StreetMetaData.jsx
  assets/scripts/streets/StreetWidth.jsx
  assets/scripts/util/date_format.js
Labels: in progress

#855 Add translated strings to BlockingError component
  assets/css/_chrome.scss
  assets/locales/en/main.json
  assets/scripts/app/App.jsx
  assets/scripts/app/BlockingError.jsx
  assets/scripts/app/__tests__/BlockingError.test.js
Labels: in progress

#889 Add angled parking to translation file
  assets/locales/en/segment-info.json
Labels: translations
