Repository streetmix/streetmix, pull requests merged in 2019-07, with the labels that each got.

#1365 refactor(Avatar): rewrite component
  assets/scripts/users/Avatar.jsx
  assets/scripts/users/__tests__/Avatar.test.js
Labels: ui

#1364 Review Barlow
  app/data/flags.json
  assets/scripts/app/flag_utils.js
  assets/scripts/dialogs/GeotagDialog.scss
  assets/scripts/info_bubble/UpDownInput.scss
  assets/scripts/menus/MenuBar.scss
  assets/styles/_typography.scss
  assets/styles/_variables.scss
Labels: not-ready

#1117 Update Mongoose to Sequelize
  .env.example
  .sequelizerc
  POSTGRESQL_SETUP_GUIDE.md
  Procfile
  app.js
  app/db/config/config.js
  app/db/migrations/20180729103314-create-user.js
  app/db/migrations/20180729103424-create-street.js
  app/db/migrations/20180729103650-create-sequence.js
  app/db/models/index.js
  app/db/models/sequence.js
  app/db/models/street.js
  app/db/models/user.js
  app/resources/v1/streets_pg.js
  app/resources/v1/users_pg.js
  app/resources/v1/users_streets_pg.js
  bin/release_tasks.sh
  config/default.js
  lib/util.js
  package-lock.json
  package.json
Labels: back-end
