Repository streetmix/streetmix, pull requests merged in 2019-05, with the labels that each got.

#1266 Enable experimental custom segment renaming.
  app/data/flags.json
  assets/locales/en/main.json
  assets/scripts/gallery/thumbnail.js
  assets/scripts/info_bubble/InfoBubble.jsx
  assets/scripts/info_bubble/InfoBubble.scss
  assets/scripts/info_bubble/__tests__/__snapshots__/InfoBubble.test.js.snap
  assets/scripts/segments/Segment.jsx
  assets/scripts/segments/SegmentLabelContainer.scss
  assets/scripts/segments/__tests__/SegmentLabelContainer.test.js
  assets/scripts/segments/__tests__/__snapshots__/SegmentLabelContainer.test.js.snap
  assets/scripts/segments/constants.js
  assets/scripts/segments/drag_and_drop.js
  assets/scripts/segments/view.js
  assets/scripts/store/actions/index.js
  assets/scripts/store/actions/street.js
  assets/scripts/store/reducers/street.js
  assets/scripts/streets/data_model.js
  assets/scripts/ui/icons.js
Labels: ready, ui

#1277 Split up StreetMetaWidth component
  assets/scripts/streets/StreetMeta.jsx
  assets/scripts/streets/StreetMeta.scss
  assets/scripts/streets/StreetMetaWidth.jsx
  assets/scripts/streets/StreetMetaWidthContainer.jsx
  assets/scripts/streets/StreetMetaWidthLabel.jsx
  assets/scripts/streets/StreetMetaWidthLabel.scss
  assets/scripts/streets/StreetMetaWidthMenu.jsx
  assets/scripts/streets/StreetMetaWidthMenu.scss
  assets/scripts/streets/__tests__/StreetMetaWidth.test.js
  assets/scripts/streets/__tests__/StreetMetaWidthContainer.test.js
  assets/scripts/streets/__tests__/StreetMetaWidthLabel.test.js
  assets/scripts/streets/__tests__/StreetMetaWidthMenu.test.js
  assets/scripts/streets/__tests__/__snapshots__/StreetMetaWidthLabel.test.js.snap
  assets/scripts/streets/__tests__/__snapshots__/StreetMetaWidthMenu.test.js.snap
  assets/scripts/streets/constants.js
Labels: code clean up, ui

#1303 Replace react-autosuggest with downshift-pelias
  assets/scripts/dialogs/Geotag/GeoSearch.jsx
  assets/scripts/dialogs/Geotag/SearchAddress.jsx
  assets/scripts/dialogs/Geotag/__tests__/GeoSearch.test.js
  assets/scripts/dialogs/Geotag/__tests__/SearchAddress.test.js
  assets/scripts/dialogs/GeotagDialog.jsx
  assets/scripts/dialogs/GeotagDialog.scss
  package-lock.json
  package.json
Labels: not-ready
